package models

var StorageConfigTemplates = map[string][]ConfigTemplate{
	"local": {
		{
			Name:        "存储路径",
			KeyName:     "base_path",
			Type:        "string",
			Required:    true,
			Description: "本地存储的基础路径",
			Default:     "uploads/files",
		},
		{
			Name:        "缩略图路径",
			KeyName:     "thumbnail_path",
			Type:        "string",
			Required:    true,
			Description: "文件缩略图存储路径",
			Default:     "uploads/thumbnails",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
	},
	"oss": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "如 oss-cn-hangzhou，通常可从 Endpoint 推导",
		},
		{
			Name:        "存储空间（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "OSS 存储空间名称（Bucket）",
		},
		{
			Name:        "Endpoint（地域节点）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "如 https://oss-cn-hangzhou.aliyuncs.com 或自定义 Endpoint",
		},
		{
			Name:        "AccessKey ID",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "阿里云访问密钥 AccessKey ID",
		},
		{
			Name:        "AccessKey Secret",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "阿里云访问密钥 AccessKey Secret",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "存储类型",
			KeyName:     "storage_class",
			Type:        "string",
			Required:    false,
			Description: "存储类型：STANDARD/IA/ARCHIVE/COLD_ARCHIVE",
			Options:     []string{"STANDARD", "IA", "ARCHIVE", "COLD_ARCHIVE"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程URL，只显示代理URL",
			Default:     "false",
		},
	},
	"s3": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "如 us-east-1，AWS S3 必填；兼容端点也建议填写",
			Default:     "us-east-1",
		},
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "S3 存储桶名称",
		},
		{
			Name:        "Endpoint（可选）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    false,
			Description: "兼容 S3 的自定义端点（如 MinIO、私有云）；AWS 可留空",
		},
		{
			Name:        "Access Key",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "访问密钥 Access Key",
		},
		{
			Name:        "Secret Key",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "访问密钥 Secret Key",
		},
		{
			Name:        "自定义域名（可选）",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链/加速域名，优先于 Endpoint",
		},
		{
			Name:        "路径样式（host/bucket/key）",
			KeyName:     "use_path_style",
			Type:        "bool",
			Required:    false,
			Description: "兼容端点常需开启路径样式；AWS 官方默认虚拟主机样式",
			Default:     "false",
		},
		{
			Name:        "访问控制（可选）",
			KeyName:     "access_control",
			Type:        "string",
			Required:    false,
			Description: "对象 ACL：public-read/private（多数情况建议用桶策略）",
			Options:     []string{"public-read", "private"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
	"cos": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "如 ap-shanghai",
		},
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "COS 存储桶名称，形如 bucketname-APPID",
		},
		{
			Name:        "SecretId",
			KeyName:     "secret_id",
			Type:        "string",
			Required:    true,
			Description: "腾讯云 API 密钥 SecretId",
		},
		{
			Name:        "SecretKey",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "腾讯云 API 密钥 SecretKey",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "访问域名（可选）",
			KeyName:     "domain",
			Type:        "string",
			Required:    false,
			Description: "COS 专用访问域名（可选）",
		},
		{
			Name:        "存储类型",
			KeyName:     "storage_class",
			Type:        "string",
			Required:    false,
			Description: "存储类型：STANDARD/MAZ_STANDARD/STANDARD_IA/MAZ_STANDARD_IA/INTELLIGENT_TIERING/MAZ_INTELLIGENT_TIERING/ARCHIVE/DEEP_ARCHIVE",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用HTTPS",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程URL，只显示代理URL",
		},
	},
	"qiniu": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    false,
			Description: "S3 兼容 Region（与 Endpoint 匹配，可留空）",
		},
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "七牛云 Kodo 存储桶名称",
		},
		{
			Name:        "Endpoint（S3 兼容）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "S3 兼容 API 终结点，如 https://s3-cn-east-1.qiniucs.com",
		},
		{
			Name:        "AccessKey",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "七牛云 AccessKey",
		},
		{
			Name:        "SecretKey",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "七牛云 SecretKey",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链域名或自定义加速域名",
		},
		{
			Name:        "路径样式（domain/bucket/key）",
			KeyName:     "use_path_style",
			Type:        "bool",
			Required:    false,
			Description: "部分自定义域名需在路径前带上 bucket，开启后生成 domain/bucket/key",
			Default:     "false",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
	"upyun": {
		{
			Name:        "服务名（Space/Service）",
			KeyName:     "service",
			Type:        "string",
			Required:    true,
			Description: "又拍云服务名（空间名）",
		},
		{
			Name:        "操作员名（Operator）",
			KeyName:     "operator",
			Type:        "string",
			Required:    true,
			Description: "又拍云操作员用户名",
		},
		{
			Name:        "操作员密码（Password）",
			KeyName:     "password",
			Type:        "password",
			Required:    true,
			Description: "用于计算签名，仅服务端存储",
		},
		{
			Name:        "Endpoint",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "REST API 端点，默认 https://v0.api.upyun.com",
			Default:     "https://v0.api.upyun.com",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链/加速域名，直链访问时使用",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，仅走系统代理",
			Default:     "false",
		},
	},
	"r2": {
		{
			Name:        "区域",
			KeyName:     "region",
			Type:        "string",
			Required:    false,
			Description: "通常填写 auto（R2 基于 Endpoint 工作）",
			Default:     "auto",
		},
		{
			Name:        "存储桶",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "R2 存储桶名称（Bucket Name）",
		},
		{
			Name:        "Endpoint",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "R2 S3 终结点，例如 https://<accountid>.r2.cloudflarestorage.com 或管辖区特定终结点",
		},
		{
			Name:        "访问密钥 ID",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "Cloudflare R2 访问密钥 ID（Access Key ID）",
		},
		{
			Name:        "机密访问密钥",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "Cloudflare R2 机密访问密钥（Secret Access Key）",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "可选：r2.dev 公共域名或自定义加速域名（公开直链时填写）",
		},
		{
			Name:        "使用HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，仅显示代理 URL（私有访问时建议开启）",
			Default:     "false",
		},
	},
	"rainyun": {
		{
			Name:        "区域",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "雨云区域，固定为rainyun",
			Default:     "rainyun",
		},
		{
			Name:        "存储桶",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "雨云对象存储桶名称",
		},
		{
			Name:        "Endpoint（API 端点）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "雨云对象存储 API 端点",
			Default:     "https://cn-sy1.rains3.com",
		},
		{
			Name:        "AccessKey",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "雨云对象存储 AccessKey",
		},
		{
			Name:        "SecretKey",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "雨云对象存储 SecretKey",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "存储类型",
			KeyName:     "storage_class",
			Type:        "string",
			Required:    false,
			Description: "存储类型：STANDARD/STANDARD_IA/GLACIER/DEEP_ARCHIVE",
			Options:     []string{"STANDARD", "STANDARD_IA", "GLACIER", "DEEP_ARCHIVE"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
}
